server:
  port: 8081
spring:
  redis:
    port: 6379
    host: localhost
  datasource:
    url: jdbc:mysql://localhost:3306/glamourbynora
    username: root
    password: password@12345
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: eb2814df09d834
    password: 96a83f9b980f78
    protocol: smtp
    properties.mail.smtp:
    auth: false
    starttls.enable: true
app:
    authType: cookie
    cookie:
      login: cookie
    session:
      login: session